const routes = {
    //Admin
    admin: '/admin',
    dashboard: '/admin/dashboard',
    navigationList: '/admin/navigation-list',
    addNavigation: '/admin/add-navigation',
    editNavigation: '/admin/edit-navigation/:id',
    productList: '/admin/product-list',
    addProduct: '/admin/add-product',
    editProduct: '/admin/edit-product/:id',
    newsList: '/admin/news-list',
    addNews: '/admin/add-news',
    updateNews: '/admin/update-news/:id',
    serviceList: '/admin/service-list',
    addService: '/admin/add-service',
    updateService: '/admin/update-service/:id',
    partnerList: '/admin/partner-list',
    addPartner: '/admin/add-partner',
    updateProject: '/admin/update-project/:id',
    projectList: '/admin/project-list',
    addProject: '/admin/add-project',
    updateUser: '/admin/update-user/:id',
    changePassword: '/admin/change-password',
    userList: '/admin/user-list',
    addUser: '/admin/add-user',
    videosList: '/admin/videos-list',
    imagesList: '/admin/images-list',
    addImage: '/admin/add-image',
    addVideo: '/admin/add-video',
    //User
    home: '/',
    about: '/gioi-thieu',
    introduction: '/gioi-thieu/tong-quan',
    history: '/gioi-thieu/lich-su-phat-trien',
    organizational: '/gioi-thieu/so-do-to-chuc',
    vision: '/gioi-thieu/tam-nhin-su-menh-gia-tri',
    capacityProfile: '/gioi-thieu/ho-so-nang-luc',
    qualityGoals: '/gioi-thieu/muc-tieu-chat-luong',
    products: '/san-pham',
    productCategory: '/san-pham/:slug',
    productDetail: '/san-pham/:category/:id',
    news: '/tin-tuc',
    newsDetail: `/tin-tuc/:category/:id`,
    newsCategory: `/tin-tuc/:slug`,
    search: '/search',
    projects: '/du-an-va-nang-luc',
    projectCategory: '/du-an-va-nang-luc/:slug',
    projectDetail: '/du-an-va-nang-luc/:category/:id',
    services: '/dich-vu',
    serviceDetail: '/dich-vu/:category/:id',
    servicesCategory: `/dich-vu/:slug`,
    teams: '/doi-ngu',
    error404: '/404',
    contact: '/lien-he',
};

export default routes;
